"""rename department

Revision ID: e0b5f984ac15
Revises: bd25ab5cbd5a
Create Date: 2024-10-01 11:24:21.263240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b5f984ac15'
down_revision = 'bd25ab5cbd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###